/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sk.vinf.cli.app

import sk.vinf.cli.app.utils.*
import org.apache.commons.text.StringEscapeUtils
import kotlin.test.Test

class AppTest {
    @Test fun testAppHasAGreeting() {
        val string = "Tristan Tzara&lt;br&gt;&lt;small&gt;Samuel  Rosenstock&lt;/small&gt;"
        val escaped = StringEscapeUtils.unescapeHtml4(string)
        println(escaped.removePattern(htmlRegex))
    }
}
